/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'AJ' at '9/22/16 11:32 AM' with Gradle 2.14.1
 *
 * @author AJ, @date 9/22/16 11:32 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
